server:
  port: 8088

spring:
  # 配置SBA Client连接的安全账号密码
  security:
    user:
      name: admin
      password: 1
  boot:
    admin:
      ui:
        title: "应用监控管理"
        brand: "<img src='assets/img/icon-spring-boot-admin.svg'><span>应用监控管理</span>"
      notify:
        mail:
          from: 202727330@qq.com
          to: tsb.j@qq.com
          cc: tsb.j@qq.com
  mail:
    host: smtp.qq.com
    port: 465
    username: 202727330@qq.com
    password: ifogocnbfxtbbiab
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
