application:
  version: 1.0-SNAPSHOT
  title: SpringBootVue

logging:
  level:
    root: info

spring:
  banner:
    location: classpath:banner/dev.txt
  thymeleaf:
    cache: false
  servlet:
    multipart:
      location: /Users/lmmarise.j/develop/java_web_project_list/SpringBootVue/app/target/temp
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  jackson:
    default-property-inclusion: ALWAYS
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    one:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql:///springboot_vue?serverTimezone=UTC
      username: root
      password: lmmgo
      driver-class-name: com.mysql.cj.jdbc.Driver
    two:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql:///springboot_vue2?serverTimezone=UTC
      username: root
      password: lmmgo
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: lmmgo
    cluster:
      urls:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
        - 127.0.0.1:7006
        - 127.0.0.1:7007
        - 127.0.0.1:7008
        - 127.0.0.1:7009
      poolConfig:
        max-total: 9
        max-idle: 9
        max-wait-millis: -1
        min-idle: 0
  boot:
    admin:
      client:
        # 注册到 SBA Server
        url: http://localhost:8088
        # SBA Server 的密码
#        username: admin
#        password: admin
        instance:
          metadata:
            # 将自己的配置发送到 SBA Server
            user.name: admin
            user.password: 1
  security:
    checkCode: false

server:
  port: 8081
  error:
    path: /error
  servlet:
    context-path: /app
    session:
      timeout: 30m
  ssl:
    key-alias: tomcathttps
    key-store: /Users/lmmarise.j/develop/java_web_project_list/SpringBootVue/app/src/main/resources/key/tomcathttps.p12.jks
    key-password: 123456
    key-store-provider: SUN

management:
  endpoint:
    health:
      roles: ADMIN
      status:
        order: FATAL,DOWN,OUT_OF_SERVICE,UP,UNKNOWN
        http-mapping:
          FATAL: 503
